import sqlite3
from pathlib import Path

DB_PATH = Path(__file__).with_name("achiki.db")

if DB_PATH.exists():
    DB_PATH.unlink()

connection = sqlite3.connect(DB_PATH)
connection.execute("PRAGMA foreign_keys = ON")

connection.executescript(
    """
CREATE TABLE Program (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  faculty TEXT,
  campus TEXT,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL
);
CREATE TABLE User (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  programId INTEGER,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  passwordHash TEXT,
  authProvider TEXT NOT NULL DEFAULT 'credentials',
  googleId TEXT UNIQUE,
  avatarUrl TEXT,
  role TEXT NOT NULL DEFAULT 'READER',
  status TEXT NOT NULL DEFAULT 'ACTIVE',
  bio TEXT,
  publicSignature TEXT,
  reviewArea TEXT,
  approvalLevel TEXT,
  systemPermissions TEXT,
  preferences TEXT,
  lastLoginAt DATETIME,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL,
  FOREIGN KEY (programId) REFERENCES Program(id) ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE TABLE Category (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL UNIQUE,
  slug TEXT NOT NULL UNIQUE,
  colorClass TEXT,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL
);
CREATE TABLE Edition (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  publishedAt DATETIME,
  status TEXT NOT NULL DEFAULT 'DRAFT',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL
);
CREATE TABLE Publication (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  authorId INTEGER NOT NULL,
  categoryId INTEGER NOT NULL,
  editionId INTEGER,
  type TEXT NOT NULL DEFAULT 'ARTICLE',
  title TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  summary TEXT NOT NULL,
  content TEXT,
  excerpt TEXT,
  featured BOOLEAN NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'DRAFT',
  publishedAt DATETIME,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL,
  FOREIGN KEY (authorId) REFERENCES User(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY (categoryId) REFERENCES Category(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY (editionId) REFERENCES Edition(id) ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX Publication_categoryId_idx ON Publication(categoryId);
CREATE INDEX Publication_authorId_idx ON Publication(authorId);
CREATE INDEX Publication_type_status_idx ON Publication(type, status);
CREATE TABLE PublicationImage (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  publicationId INTEGER NOT NULL,
  url TEXT NOT NULL,
  description TEXT,
  isPrimary BOOLEAN NOT NULL DEFAULT 0,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (publicationId) REFERENCES Publication(id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE Tag (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL UNIQUE,
  slug TEXT NOT NULL UNIQUE,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE PublicationTag (
  publicationId INTEGER NOT NULL,
  tagId INTEGER NOT NULL,
  assignedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (publicationId, tagId),
  FOREIGN KEY (publicationId) REFERENCES Publication(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (tagId) REFERENCES Tag(id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE Comment (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  publicationId INTEGER NOT NULL,
  userId INTEGER NOT NULL,
  content TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'PENDING',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (publicationId) REFERENCES Publication(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE TABLE Event (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  description TEXT,
  location TEXT,
  startsAt DATETIME NOT NULL,
  endsAt DATETIME,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL
);
CREATE TABLE EventRegistration (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  eventId INTEGER NOT NULL,
  userId INTEGER NOT NULL,
  status TEXT NOT NULL DEFAULT 'REGISTERED',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (eventId) REFERENCES Event(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  UNIQUE(eventId, userId)
);
CREATE TABLE Subscriber (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT NOT NULL UNIQUE,
  active BOOLEAN NOT NULL DEFAULT 1,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE Newsletter (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  subject TEXT NOT NULL,
  content TEXT,
  status TEXT NOT NULL DEFAULT 'DRAFT',
  sentAt DATETIME,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL
);
CREATE TABLE NewsletterDelivery (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  newsletterId INTEGER NOT NULL,
  subscriberId INTEGER NOT NULL,
  status TEXT NOT NULL DEFAULT 'PENDING',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (newsletterId) REFERENCES Newsletter(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (subscriberId) REFERENCES Subscriber(id) ON DELETE CASCADE ON UPDATE CASCADE,
  UNIQUE(newsletterId, subscriberId)
);
"""
)

connection.commit()
connection.close()
print(f"SQLite database initialized at {DB_PATH}")
